- client-side/frontend/src/App.jsx
- client-side/frontend/src/component/addEmployee/addEmployee.css
- client-side/frontend/src/component/employeelist/employeeList.css
- client-side/frontend/src/component/landing/landing.css
- client-side/frontend/src/component/updateEmployee/updateEmployee.css
**Description**: Updated the CSS file to make it mobile responsive.
Issue: Closes #7 
**Before**
**After**
**Before**
**After**
> Updated the CSS files to make them mobile responsive

- client-side/frontend/package-lock.json
- client-side/frontend/package.json
- client-side/frontend/src/App.css
- client-side/frontend/src/component/addTask/AddTask.jsx
- client-side/frontend/src/component/addTask/addTask.css
- client-side/frontend/src/component/landing/Landing.jsx
- client-side/frontend/src/component/landing/landing.css
- client-side/frontend/src/component/taskList/TaskList.jsx
- client-side/frontend/src/component/taskList/taskList.css
- client-side/frontend/src/component/updateTask/UpdateTask.css
- client-side/frontend/src/component/updateTask/UpdateTask.jsx
- client-side/frontend/src/main.jsx
- client-side/frontend/src/services/TaskService.js
Introducing the Tasks page which lets you:-
- View Tasks (Name, Description, Assigned Employees)
- Add New Tasks
- Update Tasks
Closes #13
> feat: [FRONTEND] Add Tasks UI

- client-side/frontend/src/component/updateEmployee/UpdateEmployee.jsx
> Fix: Employee Update Page does not show any initial data (#15)

- server-side/src/main/java/com/crud/serverside/controller/AttendanceController.java
- server-side/src/main/java/com/crud/serverside/model/Attendance.java
- server-side/src/main/java/com/crud/serverside/repository/AttendanceRepository.java
This PR adds the following features:-
- Adds ability to mark attendance (present or absent) status of employees on specified dates
- Adds ability to update already marked attendances
Closes #2
> feat: [Backend] Employee Attendance

- client-side/frontend/src/App.jsx
- client-side/frontend/src/component/attendance/addAttendance/AddAttendance.jsx
- client-side/frontend/src/component/attendance/addAttendance/addAttendance.css
- client-side/frontend/src/component/attendance/attendanceList/AttendanceList.jsx
- client-side/frontend/src/component/attendance/attendanceList/attendanceList.css
- client-side/frontend/src/component/attendance/updateAttendance/UpdateAttendance.jsx
- client-side/frontend/src/component/attendance/updateAttendance/updateAttendance.css
- client-side/frontend/src/component/landing/Landing.jsx
- client-side/frontend/src/main.jsx
- client-side/frontend/src/services/AttendanceService.js
This PR adds the frontend implementation of Employee Attendance
This PR adds the following components:
- Attendance List
- Add Attendance
- Update Attendance
Closes #21
> feat: [Frontend] Employee Attendance

- .github/workflows/build-frontend.yml
> [FEAT] GitHub Actions Workflow for building frontend

- server-side/src/main/java/com/crud/serverside/controller/CheckInController.java
- server-side/src/main/java/com/crud/serverside/model/CheckIn.java
- server-side/src/main/java/com/crud/serverside/repository/CheckInRepository.java
> [feat] [backend] Implement Employee Check-In

- .env.default
- client-side/frontend/package-lock.json
- client-side/frontend/package.json
- client-side/frontend/src/main.jsx
- server-side/pom.xml
- server-side/src/main/java/com/crud/serverside/controller/LoginController.java
- server-side/src/main/java/com/crud/serverside/repository/EmployeeRepository.java
- server-side/src/main/java/com/crud/serverside/service/FirebaseService.java
Added:
- Firebase Authentication
- Login Controller for handling Employee Login
- Closes #32
> [backend] Implement Firebase Authentication

- README.md
> [docs] Modify README for new instructions about setting up and running the Docker Container

- server-side/src/main/java/com/crud/serverside/controller/DepartmentController.java
- server-side/src/main/java/com/crud/serverside/model/Department.java
- server-side/src/main/java/com/crud/serverside/repository/DepartmentRepository.java
> [feat] [backend] Implement Employee Departments

- server-side/src/main/java/com/crud/serverside/controller/NotificationController.java
- server-side/src/main/java/com/crud/serverside/model/Notification.java
- server-side/src/main/java/com/crud/serverside/repository/NotificationRepository.java
> [feat] [backend] Office Notifications

- server-side/src/main/java/com/crud/serverside/controller/FeedbackController.java
- server-side/src/main/java/com/crud/serverside/model/Feedback.java
- server-side/src/main/java/com/crud/serverside/repository/FeedbackRepository.java
> [feat] [backend] Employee Feedbacks

- server-side/src/main/java/com/crud/serverside/controller/MeetingController.java
- server-side/src/main/java/com/crud/serverside/model/Meeting.java
- server-side/src/main/java/com/crud/serverside/repository/MeetingRepository.java
> [feat] [backend] Employee Meetings

- .env.default
- .github/workflows/deploy-backend.yml
- client-side/frontend/src/component/attendance/addAttendance/AddAttendance.jsx
- client-side/frontend/src/component/attendance/attendanceList/AttendanceList.jsx
- client-side/frontend/src/component/attendance/updateAttendance/UpdateAttendance.jsx
- client-side/frontend/src/component/employee/addEmployee/AddEmployee.jsx
- client-side/frontend/src/component/employee/employeelist/EmployeeList.jsx
- client-side/frontend/src/component/employee/updateEmployee/UpdateEmployee.jsx
- client-side/frontend/src/component/task/addTask/AddTask.jsx
- client-side/frontend/src/component/task/taskList/TaskList.jsx
- client-side/frontend/src/component/task/updateTask/UpdateTask.jsx
- client-side/frontend/src/constants/apiConstant.js
- client-side/frontend/src/services/AttendanceService.js
- client-side/frontend/src/services/EmployeeService.js
- client-side/frontend/src/services/TaskService.js
- server-side/src/main/java/com/crud/serverside/controller/AttendanceController.java
- server-side/src/main/java/com/crud/serverside/controller/CheckInController.java
- server-side/src/main/java/com/crud/serverside/controller/DepartmentController.java
- server-side/src/main/java/com/crud/serverside/controller/EmployeeController.java
- server-side/src/main/java/com/crud/serverside/controller/LoginController.java
- server-side/src/main/java/com/crud/serverside/controller/NotificationController.java
- server-side/src/main/java/com/crud/serverside/controller/TaskController.java
- server-side/src/main/java/com/crud/serverside/service/FirebaseService.java
This PR will allow automatic deployment of the Spring Boot backend to Azure API App Service on pushes to `main` branch
> [backend] Deploy Spring Boot Application to Azure API App Service

- server-side/src/main/resources/application.properties
- Since the SQL Server uses SSL, we need to disable insecure database connection
> Disable insecure database connection

- server-side/src/main/java/com/crud/serverside/controller/AttendanceController.java
- server-side/src/main/java/com/crud/serverside/controller/CheckInController.java
- server-side/src/main/java/com/crud/serverside/controller/DepartmentController.java
- server-side/src/main/java/com/crud/serverside/controller/EmployeeController.java
- server-side/src/main/java/com/crud/serverside/controller/FeedbackController.java
- server-side/src/main/java/com/crud/serverside/controller/LoginController.java
- server-side/src/main/java/com/crud/serverside/controller/MeetingController.java
- server-side/src/main/java/com/crud/serverside/controller/NotificationController.java
- server-side/src/main/java/com/crud/serverside/controller/TaskController.java
- server-side/src/main/resources/application.properties
- The Spring Boot deployment server was throwing a CORS error
This PR has the fix for it
> [fix] CORS Error

- server-side/src/main/java/com/crud/serverside/controller/CheckOutController.java
- server-side/src/main/java/com/crud/serverside/model/CheckOut.java
- server-side/src/main/java/com/crud/serverside/repository/CheckOutRepository.java
- Closes #56 
- Extension of #36
> [feat] [backend] Employee Check Out

- server-side/src/main/java/com/crud/serverside/controller/EventController.java
- server-side/src/main/java/com/crud/serverside/model/Event.java
- server-side/src/main/java/com/crud/serverside/repository/EventRepository.java
> [feat] [backend] Office Events

- server-side/src/main/java/com/crud/serverside/controller/SkillController.java
- server-side/src/main/java/com/crud/serverside/model/Skill.java
- server-side/src/main/java/com/crud/serverside/repository/SkillRepository.java
> [feat] [backend] Employee Skills

- server-side/src/main/java/com/crud/serverside/controller/InventoryController.java
- server-side/src/main/java/com/crud/serverside/model/Inventory.java
- server-side/src/main/java/com/crud/serverside/repository/InventoryRepository.java
> [feat] [backend] Office Inventory

- server-side/src/main/java/com/crud/serverside/model/CheckOut.java
> Fix major typo bug
